# Database settings
pg_port = 5432
pg_host = "localhost"
pg_user = "rowan"
pg_password = "postgres"
pg_dbname = "aact"

# MedDRA mapping setings
skip_meddra = true         # MedDRA requires acces to their db, if you don't have it you can still, skip the final step and still get decent outcome info.
meddra_precision = 3        # Wildness in mapping unkown meddra terms 5 least precise 1 very precies
